# Generated by Django 2.1.7 on 2019-05-07 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkslot_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parkslot_list.User'),
        ),
    ]
