# Generated by Django 2.1.7 on 2019-05-07 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkslot_list', '0002_booking_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='userid',
            new_name='user',
        ),
    ]
