# Generated by Django 2.1.7 on 2019-05-09 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkslot_list', '0003_auto_20190507_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booktime', models.DateTimeField(auto_now_add=True)),
                ('bookfrom', models.DateTimeField()),
                ('bookuntil', models.DateTimeField()),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkslot_list.List')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parkslot_list.User')),
            ],
        ),
    ]
