# Generated by Django 2.1.7 on 2019-05-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkslot_list', '0004_historybooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historybooking',
            name='user',
        ),
        migrations.AddField(
            model_name='historybooking',
            name='userid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historybooking',
            name='slot',
            field=models.CharField(max_length=4),
        ),
    ]
