# Generated by Django 2.1.7 on 2019-08-14 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkslot_list', '0007_historyoccupied'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Akun',
        ),
        migrations.RenameField(
            model_name='akun',
            old_name='name',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='akun',
            old_name='userid',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='historybooking',
            old_name='userid',
            new_name='username',
        ),
    ]
