# Generated by Django 2.1.7 on 2019-08-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkslot_list', '0008_auto_20190814_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyoccupied',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
